### ISSUE TITLE
Overlapping events not returned on iOS

### ISSUE THREAD

**Issue by drewdhutchins** [EddyVerbruggen/Calendar-PhoneGap-Plugin#112]
On my calendar I have the following events scheduled for today:

4:30 pm - 5:00 pm (Meeting 1)
4:50 pm - 5:00 pm (Phone call 1)
5:00 pm - 5:30 pm (Meeting 2)

The only event that is being returned is Meeting 2.  If I change Meeting 1 to end at 4:50 pm, all events are returned as you would expect.  Is there anyway to return all events even if they are overlapping

**Comment by EddyVerbruggen** [comment]
Hi, just tried this exact case and didn't have problems. Note that `findAllEventsInNamedCalendar` only returns future events. If your code ran at 4:51 PM then you would only get the one starting at 5:00. It got me fooled once.

If that's not it, then it must be some recent fix because it works great at the moment.
