### ISSUE TITLE
How to delete all events in android

### ISSUE THREAD

**Issue by maxvenkat** [EddyVerbruggen/Calendar-PhoneGap-Plugin#140]
Hi,
  I want to delete event that inserted using my app (sample.apk) at every installation of my app (sample.apk) 

I have tried for android

 window.plugins.calendar.deleteEvent(null, loc, null, startdate, enddate, onSuccess, onError);

but is results in false in success. So any wrong with this I have followed

is there any way for fromdate to todate for deleting 

For this in ios calendar name is there, So we can delete the calendar that we created

But for android is there any unique id or text can be followed to delete all events created from my app or else any other way is there to fix it

pls reply asap

**Comment by EddyVerbruggen** [comment]
At the moment you'll need to match your events exactly when deleting them on Android.

Since we don't yet support custom calendars on Android (like you're using on iOS) we can't simply let you remove events via wildcard titles like '*' or 'null' as all matching events would be removed - even events your app didn't create. So basically we're protecting you from not accidentally wiping the entire calendar of your users.

I can see how that's a pain in the b*tt so as of now you can delete items with a specific prefix. If you have prefixed all your event titles with the same thing you can now easily match and delete those on iOS and Android. So 'CoolApp Event: meeting' and 'CoolApp Event: phone call' would both match `window.plugins.calendar.deleteEvent('CoolApp Event: ', null, null, startdate, enddate, onSuccess, onError);`

**Comment by EddyVerbruggen** [comment]
Btw, you may have been a victim of the bug fixed with #147. Please be aware of what you delete on the user's calendar, but try again with the latest version of the plugin please.
