### ISSUE TITLE
listEventsInRange  does not fetch  All Day Events (Android)?

### ISSUE THREAD

**Issue by ramsabarish** [EddyVerbruggen/Calendar-PhoneGap-Plugin#152]
When I called this method it did not fetch any of the All Day Events, only the regular events were fetched. The below code shows how I define the Start Day, End Day and call the plugin method. 

Kindly tell me my mistake?        

    var today = new Date();   
    var dd = today.getDate();
    var mm = today.getMonth();
    var yyyy = today.getFullYear();
        
    if (dd < 10) {
        dd = '0' + dd;
    }

    if (mm < 10) {
        mm = '0' + mm;
    }

    var Startday = new Date(yyyy, mm, dd , 0,0,0,0,0);
 
    var Next_Day = parseInt(dd) + 1;
   
    if (Next_Day < 10) {
        Next_Day = '0' + Next_Day;
    }

    var EndDay = new Date(yyyy, mm, Next_Day ,0,0,0,0,0);
  
   
    mm = parseInt(mm) + 1;
    if (mm < 10) {
        mm = '0' + mm;
    }  
    
    window.plugins.calendar.listEventsInRange(Startday, EndDay, successToday, error);

**Comment by junedlanja** [comment]
reason behind it is in calender.java

Cursor cursor = contentResolver.query(l_eventUri, l_projection, "( dtstart >" + calendar_start.getTimeInMillis() + " AND dtend <" + calendar_end.getTimeInMillis() + " AND deleted = 0)", null, "dtstart ASC");

so your start date and end date should be grater than your actual event start date and end date.
For example to find event for 2nd jan your start date should be 11 jan 23:59:59 and end date should be 3 jan 00:00:01

I haven't tested it but hope it should work for you.

Note: Make sure your recurrence  event will not show up in this date range because its recurrence event , and its original date might be different.

**Comment by EddyVerbruggen** [comment]
@junedlanja That's now been changed to also include the event itself.

But also, all day events are now stored in UTC as per Android spec and `listEventInRange` will search for UTC or the user's timezone based on whether or not it's an all day event. That's transparent for the user, the Java code will take care of this oddity.

Fixes are part of 4.3.3.
