### ISSUE TITLE
Create Calendar makes pre-installed google calendar app to stop working

### ISSUE THREAD

**Issue by onkar0777** [EddyVerbruggen/Calendar-PhoneGap-Plugin#241]
Hi,
I have the following code corresponding to two buttons:
====Create Calendar=====
$scope.createCal = function(){
      $cordovaCalendar.createCalendar({
        calendarName: 'Cordova Calendar',
        calendarColor: '#FF0000'
      }).then(function (result) {
        console.log("Success - "+ result);
      }, function (err) {
        console.log("Error - "+ err);
      });
    };

====Create Event====
$scope.createCalEvent = function() {
      $cordovaCalendar.createEvent({
        title: 'Space Race',
        location: 'The Moon',
        notes: 'Bring sandwiches',
        startDate: new Date(2015, 0, 6, 18, 30, 0, 0, 0),
        endDate: new Date(2015, 1, 6, 12, 0, 0, 0, 0)
      }).then(function (result) {
        console.log("Success - "+ result);
      }, function (err) {
        console.log("Error - "+ err);
      });
    };

So I tried this on both oneplusone and oneplustwo. For both the functions I get success log - Sucess - Yes and Success - xxx (incremental number). 
But after calling create calendar the google calendar app starts crashing.

Am I doing something wrong or is it not supposed to be used this way ?

Also it will be great if someone can point me towards how to get the calendar app working.

**Comment by onkar0777** [comment]
Can someone please give some info on this? Is this supposed to happen ? Or am I doing something very wrong ?

**Comment by flieks** [comment]
i also get a crash when i go to "view calendars" in android planner app

**Comment by pvelumani** [comment]
I'm also facing the same issue. Google Calendar got crashed, when try createEventInteractively()

**Comment by pvelumani** [comment]
Pre-installed google calendar app is back, after disable Google Calendar and Google Calendar Storage, re-enable it will bring back to factory version, Later update to latest version via Google Play, It works fine

**Comment by jomarocas** [comment]
sorry but the latest comment of @pvelumani no working for me, i uninstall the app and crash, i uninstall the app and download latest version and continue dont working and only that i make install digical and working good, the calendar native dont working good

**Comment by allanpoppe** [comment]
I'm also having this issue. This is very serious.

**Comment by EddyVerbruggen** [comment]
Looking into it..

**Comment by EddyVerbruggen** [comment]
OK, that took me a while to figure out. This problem pops up because of the usage of an unsupported feature on Android: `createCalendar`, see this table in the README:

<img width="784" alt="screen shot 2016-09-11 at 11 47 15" src="https://cloud.githubusercontent.com/assets/1426370/18416448/8b53f3f8-7815-11e6-93df-be86937ea5f8.png">

Unfortunately the Android implementation was work in progress but it did create 'half a Calendar' in Android which wasn't really expected to work as the created Calendar is missing a few properties that cause the native Calendar apps to crash. IMO Android shouldn't allow creating such a Calendar in the first place because according to SO this has bitten a lot of folks in the past.

### Looking forward
I have now added FULL and official support for `createCalendar` and `deleteCalendar` which will create and delete Calendars. You can even pass in a color like on iOS. See the README for an example.

### How to fix those devices with a crashing Calendar app
Call `deleteCalendar` with any calendar name (`window.plugins.calendar.deleteCalendar("whatevernameyoulike")`). The function will try to remove Calendars by the name you pass in, as well as any previously created 'faulty' Calendars on the device, either created through your app with this plugin installed, or any other app that created an invalid Calendar. I figured that way we can auto-fix this problem for anyone affected.

Available now, in version 4.5.2.

**Comment by allanpoppe** [comment]
@EddyVerbruggen you're the man.

Unfortunately, I still have the same problem.

See the first image below. I call the window.plugins.calendar.deleteCalendar("ohmygosh") method on the 'Remove faluty calendars' button. I receive this 'yes' answer.

![Remove faulty calendars](http://goo.gl/kWqBwI)

But, when I list all calendars, I keep getting these 3 'empty' calendars:

![Show all calendars](http://goo.gl/p2cJ2O)
